name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Format
      run: cargo fmt --check

    - name: Clippy
      run: cargo clippy --tests -- -D warnings

    - name: Tests
      run: cargo test
